image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install .[docs,tests]

test:
  script:
    - tox


pages:
  script:
    - cd docs ; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - main
